title:              Shinwoo Kim
email:              shinwookim@pitt.edu
description:        A student at the University of Pittsburgh studying computer science and mathematics
author:             Shinwoo Kim
baseurl:            "/~shk148"
url:                "https://sites.pitt.edu"


# Social Profiles
twitter_username:   _shinwookim
github_username:    shinwookim
facebook_username:  shinwoo.k73
instagram_username: _shinwookim 
linkedin_username: kimshinwoo

# Build settings
markdown:           kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
paginate:           5
paginate_path:      "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
include:
  - _pages